services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "30.0.0.1:8081:80"
    volumes:
      - ./data:/srv
      - ./database.db:/database.db
    command: ["-d", "/database.db", "-p", "80"]
    networks:
      - portal
    environment:
      - TZ=Europe/Berlin
    user: "0:0"

networks:
  portal:
    external: true
