apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: antlers
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: grafana-secret
  data:
    - secretKey: admin-user
      remoteRef:
        key: services/grafana
        property: admin_user
    - secretKey: admin-password
      remoteRef:
        key: services/grafana
        property: admin_password
