apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: antlers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      nodeSelector:
        kubernetes.io/hostname: 282067.fornex.cloud
      hostNetwork: true
      containers:
        - name: coredns
          image: coredns/coredns:latest
          args:
            - -conf
            - /Corefile
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /Corefile
              subPath: Corefile
      volumes:
        - name: config
          configMap:
            name: coredns-config
