apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  namespace: antlers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      nodeSelector:
        role: hub
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: synapse
          image: matrixdotorg/synapse:latest
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: /data/homeserver.yaml
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: matrix-synapse-secret
                  key: postgres-password
            - name: REGISTRATION_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: matrix-synapse-secret
                  key: registration-shared-secret
            - name: MACAROON_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: matrix-synapse-secret
                  key: macaroon-secret-key
            - name: FORM_SECRET
              valueFrom:
                secretKeyRef:
                  name: matrix-synapse-secret
                  key: form-secret
          ports:
            - containerPort: 8008
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /data/homeserver.yaml
              subPath: homeserver.yaml
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: matrix-synapse-data
        - name: config
          configMap:
            name: synapse-config
