services:
  web:
    image: jitsi/web:stable-9584
    container_name: jitsi-web
    restart: unless-stopped
    ports:
      - "30.0.0.1:8443:443"
      - "30.0.0.1:8000:80"
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - ENABLE_LETSENCRYPT=0
      - ENABLE_HTTP_REDIRECT=0
      - ENABLE_TRANSCRIPTIONS=0
      - DISABLE_HTTPS=0
      - JICOFO_AUTH_USER=focus
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_BOSH_URL_BASE=http://prosody:5280
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - TZ=Europe/Moscow
      - PUBLIC_URL=https://10.0.0.1:8443
    volumes:
      - ~/.jitsi-meet-cfg/web:/config:Z
    networks:
      - jitsi-net
      - portal

  prosody:
    image: jitsi/prosody:stable-9584
    container_name: jitsi-prosody
    restart: unless-stopped
    expose:
      - '5222'
      - '5347'
      - '5280'
    environment:
      - AUTH_TYPE=internal
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - GLOBAL_MODULES=
      - GLOBAL_CONFIG=
      - LDAP_URL=
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_MODULES=
      - XMPP_MUC_MODULES=
      - XMPP_INTERNAL_MUC_MODULES=
      - JICOFO_COMPONENT_SECRET=VAULT_MANAGED
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=VAULT_MANAGED
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=VAULT_MANAGED
      - JIGASI_XMPP_USER=
      - JIGASI_XMPP_PASSWORD=
      - JIBRI_XMPP_USER=
      - JIBRI_XMPP_PASSWORD=
      - JIBRI_RECORDER_USER=
      - JIBRI_RECORDER_PASSWORD=
      - TZ=Europe/Moscow
    volumes:
      - ~/.jitsi-meet-cfg/prosody/config:/config:Z
      - ~/.jitsi-meet-cfg/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
    networks:
      - jitsi-net
      - portal

  jicofo:
    image: jitsi/jicofo:stable-9584
    container_name: jitsi-jicofo
    restart: unless-stopped
    volumes:
      - ~/.jitsi-meet-cfg/jicofo:/config:Z
    environment:
      - AUTH_TYPE=internal
      - ENABLE_AUTH=0
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_SERVER=prosody
      - JICOFO_COMPONENT_SECRET=VAULT_MANAGED
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=VAULT_MANAGED
      - JVB_BREWERY_MUC=jvbbrewery
      - JIGASI_BREWERY_MUC=
      - JIBRI_BREWERY_MUC=
      - JIBRI_PENDING_TIMEOUT=
      - TZ=Europe/Moscow
    depends_on:
      - prosody
    networks:
      - jitsi-net
      - portal

  jvb:
    image: jitsi/jvb:stable-9584
    container_name: jitsi-jvb
    restart: unless-stopped
    ports:
      - "30.0.0.1:10000:10000/udp"
    environment:
      - DOCKER_HOST_ADDRESS=10.0.0.1
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_SERVER=prosody
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=VAULT_MANAGED
      - JVB_BREWERY_MUC=jvbbrewery
      - JVB_PORT=10000
      - JVB_STUN_SERVERS=stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
      - JVB_ENABLE_APIS=rest
      - TZ=Europe/Moscow
    volumes:
      - ~/.jitsi-meet-cfg/jvb:/config:Z
    depends_on:
      - prosody
    networks:
      - jitsi-net
      - portal

networks:
  jitsi-net:
    driver: bridge
  portal:
    external: true
