[Interface]
Address = 30.0.0.2/24
PrivateKey = VAULT_MANAGED
Table = off

PostUp = ip rule add from 10.0.0.0/24 table wgclients
PostUp = ip route add 30.0.0.0/24 dev wg0 table wgclients
PostUp = ip route add default dev wg2 table wgclients
PostUp = iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -o wg2 -j MASQUERADE
PostUp = iptables -I INPUT -p tcp --dport 80 -s 30.0.0.0/24 -j ACCEPT
PostUp = iptables -I INPUT -p tcp --dport 80 -s 10.0.0.0/24 -j ACCEPT
PostUp = iptables -I INPUT -p udp --dport 53 -s 30.0.0.0/24 -j ACCEPT
PostUp = iptables -I INPUT -p udp --dport 53 -s 10.0.0.0/24 -j ACCEPT
PostUp = iptables -I INPUT -p tcp --dport 53 -s 30.0.0.0/24 -j ACCEPT
PostUp = iptables -I INPUT -p tcp --dport 53 -s 10.0.0.0/24 -j ACCEPT
PostUp = iptables -A INPUT -p udp --dport 53 -j DROP
PostUp = iptables -A INPUT -p tcp --dport 53 -j DROP

PostDown = ip rule del from 10.0.0.0/24 table wgclients
PostDown = ip route del 30.0.0.0/24 dev wg0 table wgclients
PostDown = ip route del default dev wg2 table wgclients
PostDown = iptables -t nat -D POSTROUTING -s 10.0.0.0/24 -o wg2 -j MASQUERADE
PostDown = iptables -D INPUT -p tcp --dport 80 -s 30.0.0.0/24 -j ACCEPT
PostDown = iptables -D INPUT -p tcp --dport 80 -s 10.0.0.0/24 -j ACCEPT
PostDown = iptables -D INPUT -p udp --dport 53 -s 30.0.0.0/24 -j ACCEPT
PostDown = iptables -D INPUT -p udp --dport 53 -s 10.0.0.0/24 -j ACCEPT
PostDown = iptables -D INPUT -p tcp --dport 53 -s 30.0.0.0/24 -j ACCEPT
PostDown = iptables -D INPUT -p tcp --dport 53 -s 10.0.0.0/24 -j ACCEPT
PostDown = iptables -D INPUT -p udp --dport 53 -j DROP
PostDown = iptables -D INPUT -p tcp --dport 53 -j DROP

Jc = 6
Jmin = 8
Jmax = 80
S1 = 21
S2 = 126
H1 = 664839111
H2 = 1485638111
H3 = 1457145111
H4 = 1956374111

[Peer]
PublicKey = oAIW/xgDzn5YVoFYkXn5exq5VOlT3y/BlGqskmG0EhQ=
Endpoint = 31.172.71.140:51821
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
