apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jitsi-secret
  namespace: antlers
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: jitsi-secret
  data:
    - secretKey: jicofo-component-secret
      remoteRef:
        key: services/jitsi
        property: jicofo_component_secret
    - secretKey: jicofo-auth-password
      remoteRef:
        key: services/jitsi
        property: jicofo_auth_password
    - secretKey: jvb-auth-password
      remoteRef:
        key: services/jitsi
        property: jvb_auth_password
