apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: antlers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      nodeSelector:
        role: hub
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:latest
          args: ["--database", "/db/database.db", "--port", "80"]
          env:
            - name: TZ
              value: Europe/Berlin
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: srv
              mountPath: /srv
            - name: db
              mountPath: /db
      volumes:
        - name: srv
          persistentVolumeClaim:
            claimName: filebrowser-srv
        - name: db
          persistentVolumeClaim:
            claimName: filebrowser-db
