apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-srv
  namespace: antlers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-db
  namespace: antlers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
